logger:
  file:
    path: /var/log/open5gs/hss.log
  level: info

global:
  max:
    ue: 1024

hss:
  freeDiameter: /etc/freeDiameter/hss.conf
  sbi:
    server:
      - address: 127.0.0.8
        port: 7777

db_uri: mongodb://127.0.0.1:27017/open5gs
