services:
  epc:
    container_name: epc
    hostname: epc
    image: ghcr.io/opkcp/srsran_4g:latest
    command: srsepc
    networks:
      tr-network:
        ipv4_address: 172.18.0.2
    volumes:
      - ..\srsran_configs:/etc/srsran:ro
      - ..\logs:/var/log/srsran
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped

  enb:
    container_name: enb
    hostname: enb
    image: ghcr.io/opkcp/srsran_4g:latest
    command:
      - srsenb # Запуск базовой станции eNodeB
      - /etc/srsran/enb.conf # Основной файл конфигурации
    networks:
      tr-network:
        ipv4_address: 172.18.0.3
    volumes:
      - ..\srsran_configs:/etc/srsran:ro
      - ..\uhd_images:/usr/share/uhd/images
      - ..\logs:/var/log/srsran
    privileged: true
    restart: unless-stopped

networks:
  tr-network:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.18.0.0/24
