[mme]
mme_code = 0x1a  # 8-битный код MME
mme_group = 0x0001  # 16-битный идентификатор группы MME
tac = 0x0007  # 16-битный код зоны отслеживания
mcc = 250  # Мобильный код страны
mnc = 63  # Мобильный код сети
mme_bind_addr = 172.18.0.2  # IP-адрес для приёма S1-MME соединений от eNB
apn = IS2026.net  # Точка доступа (Access Point Name)
dns_addr = 8.8.8.8  # DNS-сервер для UE
encryption_algo = EEA0  # Алгоритм шифрования NAS
integrity_algo = EIA1  # Алгоритм контроля целостности NAS
paging_timer = 15  # Таймер пейджинга T3413 (с)
request_imeisv = false  # Запрашивать IMEI-SV у UE
lac = 0x0006  # 16-битный код зоны местоположения
full_net_name = IS2026  # Полное отображаемое имя сети

[hss]
db_file = user_db.csv  # Файл с информацией об абонентах

[spgw]
gtpu_bind_addr   = 172.18.0.2  # IP-адрес для привязки GTP-U
sgi_if_addr      = 10.0.0.1  # IP-адрес TUN-интерфейса SGi
sgi_if_name      = srs_spgw_sgi  # Имя TUN-интерфейса SGi
max_paging_queue = 100  # Макс. пакетов в очереди пейджинга (на UE)

[pcap]
enable   = false  # Включить захват пакетов
filename = /tmp/epc.pcap  # Путь к файлу захвата

[log]
all_level   = warning  # Уровень логирования для всех слоёв
all_hex_limit = 32  # Лимит hex-дампа
filename    = /var/log/srsran/epc.log  # Путь к файлу лога
file_max_size = -1  # Макс. размер файла (КБ); -1 = один файл
